spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user/(?<segment>.*), /api/v1/user/${segment}

        - id: service-booking
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/booking/**
          filters:
            - RewritePath=/api/v1/booking/(?<segment>.*), /api/v1/booking/${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway